fixtures:
  forge_modules:
    archive:
      repo: "puppet/archive"
      ref: "1.3.0"
    dirtree:
      repo: "AlexCline/dirtree"
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    inifile: "https://github.com/puppetlabs/puppetlabs-inifile.git"
    java_ks: "https://github.com/puppetlabs/puppetlabs-java_ks.git"
  symlinks:
    rundeck: "#{source_dir}"
